### ISSUE TITLE
ToDo to 1.0.0

### ISSUE THREAD

**Issue by kekyo** [kekyo/GitReader#7]
- [x] Reduces Task switching costs.
  - [x] `StreamReader`
  - [ ] ~~`DeflateStream` (optional, may not be implemented)~~
- [x] Completion for large repository tests. (Whether the data is corrupt or not)
  - [x] Commit messages, metadatas.
  - [x] Blob streams.
- [ ] ~~Makes configurable minor execution parameters.~~
- [x] Minor interface changing.

Other features will be considered after 1.0.0.

**Comment by kekyo** [comment]
@jairbubbles Thanks for all your contributions, it's not a big issue regarding minor interface changing, but there's a point I've been wondering about and I'd like to get your opinion.

### Branch properties

The current interface separates branch references with explicit symbolic names.

* Local branches: `Repository.Branches`.
* Remote branches: `Repository.RemoteBranches`.

Do you think this should be separated by `IsRemote` like libgit2sharp? I personally feel either way is fine, but I'm also willing to change it if there are situations where it would be clearly useful.

### Tags

Currently, as visualized in the benchmark, I think there is a loading cost for tag information in the time spent on `OpenStructuredAsync`. Branching has been improved by the previous fix, but for tags, it is necessary to identify the instance type depending on whether the tag type is Commit or not, which leads to a cost.

An idea to improve this would be to separate Annotated tags and introduce something like `Tag.GetAnnotationAsync`. I don't think that referencing annotations is a very common operation, so I have no problem with separating them in this way. On the other hand, there are cases where tags are other than Commit tags, and we cannot provide `GetCommitAsync` type-safely unless a distinction is made between these in advance.

Do you think it would be better to compromise on the latter (an exception is thrown if it is not a Commit tag at runtime) and remove `CommitTag` in favor of a single `Tag` class?

**Comment by jairbubbles** [comment]
> Do you think this should be separated by IsRemote like libgit2sharp? 

I think it's fine too if there is no perf penalty involved. For instance if it was methods `GetLocalBranchesAsync` / `GetRemoteBranchesAsync` it would be slower when you need all branches.

But as discussed before I don't think the `OpenStructuredAsync` should read everything.

> An idea to improve this would be to separate Annotated tags and introduce something like Tag.GetAnnotationAsync.

Regarding tags I think we can optimize by looking in packed-refs if the tag is peeled or not. When it's peeled we wouldn't need to resolve it later on.

That being said annoted tags are clearly not common so I would prefer to have a different method to get them.

> Do you think it would be better to compromise on the latter (an exception is thrown if it is not a Commit tag at runtime) and remove CommitTag in favor of a single Tag class?

As for tags on other things than commits, I didn't know it was possible and I have never seen usages of them. I feel like it would be ok to completely not support them for the moment.

I'm not sure about the exception couldn't we have a method to resolved the target object and check if it's a commit. I think it's like that in libGit2Sharp.


```csharp
foreach(var tag in repository.GetTagsAsync())
{
  var gitObject = await tag.GetTargetObjectAsync();
  if (gitObject is Commit)
  {
  }
}
```

**Comment by kekyo** [comment]
The version 1.0.0 being deployed!

Strucutured interface tags do not cause extra loading by looking at peeled-tags. However, since peeled-tag information is not always generated by official git client, unknown tags with no peeled-tag will load when opened.
If we want to avoid this, or if we are using the system in a processing time-sensitive environment, we have decided to have we use the primitive interface.
